webitel/webitel-ui-sdk

src/modules/Userinfo/classes/ApplicationsAccess.js

feature: adding a chat gateways component [WTEL-1992]

---

src/locale/ru/ru.js
src/locale/ua/ua.js

fix: name bag fixes[WTEL-2825]

---

package.json
src/modules/AgentStatusSelect/components/wt-cc-agent-status-select.vue

added logic for listening changed event and closed event separately

hotfix: changed wt-cc-agwnt-status-select [WTEL-4982]

---

package.json
src/components/transitions/wt-transition.vue

(https://webitel.atlassian.net/browse/WTEL-5103)

feature: change transition duration in wt-transition.vue [WTEL-5103]

---

package-lock.json
package.json

(https://webitel.atlassian.net/browse/WTEL-6131)

fix: update styleguide sdk [WTEL-6131]

---

package.json
src/modules/Filters/v2/filters/components/config/dynamic-filter-config-form.vue

(https://webitel.atlassian.net/browse/WTEL-6369)

fix: reset filter config form validation on filter name update [WTEL-6369]

---

src/components/wt-navigation-bar/wt-navigation-bar.vue

Суть задачі - це зробити лого в боковій  навігації лінкою, яка веде на стратову стрінку кожної з аплікацій.

feature: add clickable app logo support [WTEL-6160]

---

package-lock.json
package.json
src/components/transitions/wt-transition.vue

[DES-535] (https://webitel.atlassian.net/browse/DES-535)
[DES-535]: https://webitel.atlassian.net/browse/DES-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: added scss variables to duration in wt-transition.vue [DES-535]

---

package.json
src/components/transitions/cases/wt-replace-transition.vue

(https://webitel.atlassian.net/browse/DES-535)

fix: change default duration in wt-replace-transition.vue [DES-535]

---

package.json
src/components/wt-logo/wt-logo.vue

Поміняв router-link на anchor, бо зрозумів що нам треба перейти на іншу сторінку...

fix: replace router-link by anchor [WTEL-6423]

---

docs/pages/webitel-ui/components/wt-rounded-action/wt-rounded-action-docs.vue
package.json
src/components/wt-rounded-action/wt-rounded-action.vue

(https://webitel.atlassian.net/browse/WTEL-6720)

fix: add iconPrefix prop to rounded-action  [WTEL-6720] 

---

package.json
src/locale/en/en.js
src/locale/ru/ru.js
src/locale/ua/ua.js

(https://webitel.atlassian.net/browse/WTEL-6860)

feature: add locale for notification [WTEL-6860]

---

package.json
src/locale/en/en.js
src/locale/ru/ru.js
src/locale/ua/ua.js

Reverts webitel/webitel-ui-sdk#612

Revert "feature: add locale for notification [WTEL-6860]"

---

package-lock.json
package.json

Feat/wtel 7274/adding checkbox from primevue

---

package-lock.json
package.json

chore: update styleguide version to 24.12.57

---

package-lock.json
package.json

chore: update styleguide version to 24.12.59

---

src/components/on-demand/wt-display-chip-items/wt-display-chip-items.vue
src/components/wt-context-menu/wt-context-menu.vue
src/components/wt-popover/wt-popover.vue
src/plugins/primevue/primevue.scss
src/plugins/primevue/theme/components/popover/popover.scss

Fix/wtel 7431/fix chips visualization

---

src/enums/ProcessingTableColumnType/ProcessingTableColumnType.enum.js

* [WTEL-7421](https://webitel.atlassian.net/browse/WTEL-7421)
* 
[WTEL-7421]: https://webitel.atlassian.net/browse/WTEL-7421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

hotfix: add TableColumnType enum for column type definitions [WTEL-7421]

---

packages/ui-datalist/src/modules/filters/components/config/dynamic-view/dynamic-filter-config-view.vue
packages/ui-datalist/src/modules/filters/components/preview/dynamic-filter-preview.vue
src/components/wt-popover/wt-popover.vue

Hotfix/wtel 7451/filters preview

---

src/plugins/primevue/theme/components/components.js

fix: add coma in exports

---

packages/ui-datalist/package-lock.json
packages/ui-datalist/package.json
packages/ui-datalist/src/modules/filters/components/preview/dynamic-filter-preview-info.vue

Fix/wtel 7493/filters preview typography

---

package-lock.json
package.json

chore: update styleguide version to 24.12.64

---

src/api/websocket/WebSocketClientController.ts
src/api/websocket/enums/WebSocketClientEvent.ts

(https://webitel.atlassian.net/browse/WTEL-7532)
* [WT-XXXX]()
*

refactoring: extract WebSocketClientEvent to a separate file [WTEL-7532]

---

docs/pages/packages/ui-sdk/index.md

(https://webitel.atlassian.net/browse/WTEL-7532)
* [WT-XXXX]()
*

refactoring: add WebSocket documentation link to index [WTEL-7532]

---

package-lock.json
package.json

chore: update styleguide version to 24.12.66

---

package-lock.json
package.json

chore: update styleguide version to 24.12.73
